"""Stage 01c -- the automatic revision log, rendered from the committed TSV.

A page carrying `<!-- dr:revlog -->` gets a two-column table -- when a change
landed, and what it said -- drawn from a tab-separated file sitting beside it.

ONE CANONICAL LOG, AND THIS FILE NO LONGER PRODUCES IT (2026-08-04, Michael:
"make it one canonical version served by the local repo worker on every doc
commit and make that the display in the actual rendered 2 column version").

The log is generated by a workflow in the CONTENT repo, which regenerates
`automatic-revision-log.tsv` from `git log` on every doc commit. This module's
only job is to draw it. So:

    the content repo's workflow  ->  WRITES the log, on every commit
    this module                  ->  READS it, at publish time

WHAT THAT REPLACED, because the previous shape was defensible and this one is
still better. This module used to shell out to `git log` itself and generate a
SECOND TSV into the site output. Two producers, one subject: same columns, two
freshnesses, two implementations of the same parsing, and a reader who
downloaded the wrong one got an answer that was correct and stale with nothing
on the page to tell them which they had.

WHAT THIS MODULE LOST, and every one of them was a real failure mode rather
than a line of code:

  * **the git subprocess.** No `git` invocation, so no dependency on the
    content checkout being a git repo at all.
  * **the shallow-clone trap**, which was the single most dangerous thing in
    the old file. A CI checkout defaults to depth 1, `git log` does not error on
    a shallow repo -- it returns the handful of commits it holds -- and the
    result rendered as a complete-looking history covering an afternoon. That
    entire class is gone: a file is a file at any clone depth. ⚠️ The trap now
    lives in the content repo's workflow, which is the only place that still
    reads history, and it is documented there.
  * **`on_post_build`.** Nothing is generated, so there is nothing to write
    after the build. ⚠️ `hooks/01c_revlog.py` imported that function BY NAME,
    so removing it without editing the hook would have been an ImportError that
    took down every stage after 01c.

WHAT IT COSTS, stated plainly: the table is as fresh as the last PUBLISH, while
the file it is drawn from is as fresh as the last COMMIT. That is not two
datasets disagreeing any more -- it is ONE dataset, published at a lag, which
is simply what a static site is. The page says so in its own words, and the
download link goes to the copy published beside it.

🚫 STILL TWO COLUMNS ON THE PAGE. The file carries four -- `when`, `commit`,
`pr`, `change` -- and the table shows the first and last. The house rule is
that a rendered site never advertises a route back to its source (LOCKED
2026-08-03; see instance.py and base.css, which remove the repo widget twice
over), and a hash column would walk that back in through a side door. A hash
inside a file somebody downloaded is a different object: nothing is clickable
and nothing composes into a URL. **A commit column appearing in `_table()` is
the lock being reversed and needs Michael, not a tidy-up.**

⚠️ COLUMNS ARE FOUND BY HEADER NAME, NEVER BY POSITION, and that is deliberate
rather than fussy. Two repositories now have to agree on this file's shape: one
writes it, one draws it, and they ship independently. Position-based parsing
would survive a column being inserted and silently render commit hashes in the
Change column -- a page that looks fine and says the wrong thing. By name, an
unexpected order is harmless and a MISSING column is a visible error.

⚠️ THE DOWNLOAD HREF IS DERIVED FROM `dest_uri`, WHICH IS THE WHOLE FIX FOR A
BUG THIS FEATURE HAD TWICE IN ONE DAY. The file lives beside the page's SOURCE
(`01-utility/automatic-revision-log.tsv`) while the page is SERVED one level
deeper (`/01-utility/automatic-revision-log/`), so a bare relative link to its
own name resolves into a directory that does not contain it and 404s. Computing
the href with `relpath` from the page's real output directory is correct under
`use_directory_urls` either way, so the class of bug is closed rather than the
instance -- the same shape as the root-index link bug fixed the day before.
"""

from __future__ import annotations

import html
import posixpath
import re
from pathlib import Path

from . import state

#: `<!-- dr:revlog -->` or `<!-- dr:revlog some-other-name.tsv -->`.
#: The filename is optional because every site in the family uses the default;
#: it is ACCEPTED because the engine must not know a particular content repo's
#: layout, and a hardcoded path would be exactly that knowledge.
_MARKER = re.compile(
    r"[ \t]*<!--[ \t]*dr:revlog(?:[ \t]+(?P<name>[^\s>]+?))?[ \t]*-->[ \t]*"
)

_DEFAULT = "automatic-revision-log.tsv"

#: The two the table draws, by header name. `commit` and `pr` are read past on
#: purpose -- see the lock in the docstring.
_WHEN = "when"
_CHANGE = "change"


def _when(iso: str) -> str:
    """`2026-08-03T23:31:07-04:00` -> `2026-08-03  11:31p`.

    Deliberately the same shape as the hand-written log this sits beside, so
    the two read as one habit rather than two systems. An unparseable stamp is
    returned untouched rather than blanked: showing the raw value makes a
    format change visible, hiding it makes the column quietly wrong.
    """
    date, _, rest = iso.partition("T")
    hh, _, rest = rest.partition(":")
    mm = rest[:2]
    try:
        hour = int(hh)
    except ValueError:
        return iso
    suffix = "a" if hour < 12 else "p"
    twelve = hour % 12 or 12
    return date + "  " + str(twelve) + ":" + mm + suffix


def _error(message: str) -> str:
    state.note("notes", "revision log: " + message)
    return (
        '<p class="docrender-dead">Revision log unavailable: '
        + html.escape(message) + "</p>"
    )


def _read(path: Path) -> tuple[list[tuple[str, str]], str | None]:
    """Parse the TSV into (when, change) pairs. Second value is an error."""
    try:
        text = path.read_text(encoding="utf-8-sig")
    except (OSError, UnicodeDecodeError) as problem:
        return [], path.name + " could not be read (" + str(problem) + ")"

    lines = [line for line in text.splitlines() if line.strip()]
    if not lines:
        return [], path.name + " is empty"

    header = [cell.strip().lower() for cell in lines[0].split("\t")]
    try:
        when_at = header.index(_WHEN)
        change_at = header.index(_CHANGE)
    except ValueError:
        return [], (
            path.name + " has no '" + _WHEN + "' and '" + _CHANGE
            + "' columns, so it is not a revision log. Found: "
            + ", ".join(header)
        )

    rows = []
    for line in lines[1:]:
        cells = line.split("\t")
        if len(cells) <= max(when_at, change_at):
            # A short row is skipped rather than padded. Padding would invent a
            # blank change for a real timestamp, which reads as "something
            # happened and nobody knows what" -- a claim the file never made.
            continue
        rows.append((cells[when_at].strip(), cells[change_at].strip()))

    if not rows:
        return [], path.name + " has a header and no revisions"
    return rows, None


def _table(rows: list[tuple[str, str]], href: str, name: str) -> str:
    out = [
        '<div class="dr-data dr-revlog">',
        # The class is load-bearing, not decorative: Material styles
        # `table:not([class])` with `display: block`, which destroys the
        # internal table layout. Same note as datatable.py.
        '<table class="dr-data__table">',
        "<thead><tr><th>When</th><th>Change</th></tr></thead>",
        "<tbody>",
    ]
    for stamp, change in rows:
        out.append(
            "<tr><td>" + html.escape(_when(stamp)) + "</td><td>"
            + html.escape(change) + "</td></tr>"
        )
    out.append("</tbody></table>")
    out.append(
        '<p class="dr-data__source">' + str(len(rows)) + " revisions &middot; "
        + '<a href="' + html.escape(href) + '" download>' + html.escape(name)
        + "</a></p>"
    )
    out.append("</div>")
    return "\n".join(out)


def on_page_markdown(markdown, page, config, files):
    found = _MARKER.search(markdown)
    if not found:
        return markdown

    name = found.group("name") or _DEFAULT
    path = Path(page.file.abs_src_path).parent / name

    if not path.is_file():
        block = _error(
            name + " is not in the content repo beside this page. It is "
            "generated there by the revision-log workflow, so either that "
            "workflow has never run or the file was moved."
        )
        return _MARKER.sub(lambda _: block, markdown)

    rows, problem = _read(path)
    if problem:
        block = _error(problem)
        return _MARKER.sub(lambda _: block, markdown)

    # Where the page is SERVED from, versus where the file SITS. These differ by
    # one level under `use_directory_urls: true` and not at all under `false`,
    # which is exactly why this is computed rather than written by hand.
    served_from = posixpath.dirname(page.file.dest_uri)
    file_at = posixpath.join(posixpath.dirname(page.file.src_uri), name)
    href = posixpath.relpath(file_at, served_from) if served_from else file_at

    state.REVLOG = rows
    block = _table(rows, href, name)
    return _MARKER.sub(lambda _: block, markdown)
