"""Hook 04 -- look, assembled from data rather than written as code.

The palette lives in theme/*.tsv as named tokens and an instance picks a theme
by NAME in its site.yml. This turns the chosen rows into CSS custom properties
and hands them to assets.py as a generated stylesheet.

Why data and not one stylesheet per site: one stylesheet per site is three
stylesheets that drift, and the drift is invisible until somebody notices two
sites disagree about what a warning looks like. A table of tokens can be read
side by side.

What is deliberately NOT shared: the sites must not look identical. A shared
PALETTE means the day someone edits a colour to fix one site is the day another
breaks in a way nobody notices for a month. So the TOKEN NAMES are shared and
the VALUES are per instance. Structure shared, look local.

contrast.tsv is not decoration. It is the measured accessibility floor, and a
palette that drops below it gets reported.
"""

from __future__ import annotations

from . import state
from .util import load_tsv


def _rows(name: str) -> list[dict]:
    return load_tsv(state.ENGINE_ROOT / "theme" / name)


def build_css() -> str:
    """Return the generated custom-property sheet for the active instance."""
    wanted = state.INSTANCE.get("theme", "base")
    themes = {r.get("theme") for r in _rows("themes.tsv")}
    if wanted not in themes:
        known = ", ".join(sorted(t for t in themes if t)) or "none"
        state.note(
            "notes",
            "theme '" + str(wanted) + "' is not in theme/themes.tsv; falling "
            "back to 'base'. Known: " + known,
        )
        wanted = "base"

    slug = str(state.INSTANCE.get("slug", "?"))
    lines = [
        "/* GENERATED by docrender/theme.py -- do not edit.",
        "   Values come from theme/*.tsv and instances/" + slug + "/theme.css. */",
    ]

    for scheme, selector in (
        ("dark", '[data-md-color-scheme="slate"]'),
        ("light", '[data-md-color-scheme="default"]'),
    ):
        decls = []
        for row in _rows("colors.tsv"):
            if row.get("theme") not in (wanted, "base"):
                continue
            token = row.get("token") or ""
            value = row.get(scheme) or ""
            if token and value:
                decls.append("  --dr-" + token + ": " + value + ";")
        if decls:
            lines.append(selector + " {")
            lines.extend(decls)
            lines.append("}")

    typography = []
    for row in _rows("typography.tsv"):
        token = row.get("token") or ""
        value = row.get("value") or ""
        if token and value:
            typography.append("  --dr-" + token + ": " + value + ";")
    if typography:
        lines.append(":root {")
        lines.extend(typography)
        lines.append("}")

    for row in _rows("contrast.tsv"):
        try:
            ratio = float(row.get("ratio") or 0)
            floor = float(row.get("min") or 0)
        except ValueError:
            continue
        if ratio and floor and ratio < floor:
            state.note(
                "notes",
                "contrast: " + str(row.get("pair", "?")) + " measures "
                + str(ratio) + " against a floor of " + str(floor)
                + ". Readers with low vision lose this text.",
            )

    return "\n".join(lines) + "\n"
